name: "Label and Title by System on PR"

on:
  pull_request:
    types: [opened, edited]

permissions:
  issues: write
  pull_requests: write

jobs:
  process-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Label PR and set title
        uses: actions/github-script@v7
        with:
          script: |
            const systemLabels = [
              'socket',
              'mqtt',
              'coap',
              'bluecherry',
              'http',
              'parser',
              'modem',
              'other'
            ];

            const body = context.payload.pull_request.body || "";

            function extractSection(title) {
              const regex = new RegExp(`##\\s+${title}\\s*\\n+([^#]+)`, 'i');
              const match = body.match(regex);
              return match ? match[1].trim().toLowerCase() : null;
            }

            function detectTypeFromChecklist() {
              if (/\- \[[xX]\] fix/.test(body)) return "fix";
              if (/\- \[[xX]\] feature/.test(body)) return "feat";
              return "feat";
            }

            const systemRaw = extractSection("System or Component") || "other";
            const systems = systemRaw
              .split(/[\s,]+/)
              .filter(s => systemLabels.includes(s));

            const systemLabelsToAdd = systems.length > 0 ? systems : ["other"];
            const shortDesc = extractSection("Short Description") || "unspecified";
            const type = detectTypeFromChecklist();

            // Add system labels
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: systemLabelsToAdd
            });

            // Compose title with comma separated systems
            const systemPart = systemLabelsToAdd.join(", ");
            const newTitle = `${type}(${systemPart}): ${shortDesc}`;

            // Update PR title
            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              title: newTitle
            });
